MAIN_ONLY_ABILITIES = [
    "comeback",
    "last_ditch_effort",
    "opening_gambit",
    "tenacity",
    "ability_doubler",
    "haunt",
    "ninja_squid",
    "respawn_punisher",
    "thermal_ink",
    "drop_roller",
    "object_shredder",
    "stealth_jump",
]
STANDARD_ABILITIES = [
    "ink_recovery_up",
    "ink_resistance_up",
    "ink_saver_main",
    "ink_saver_sub",
    "intensify_action",
    "quick_respawn",
    "quick_super_jump",
    "run_speed_up",
    "special_charge_up",
    "special_power_up",
    "special_saver",
    "sub_power_up",
    "sub_resistance_up",
    "swim_speed_up",
]
BUCKET_THRESHOLDS = [3, 10, 20, 30, 40, 50, 57]
