method: bayes
metric:
  name: val_mse_loss
  goal: minimize

parameters:
  usage_coeff:
    distribution: log_uniform_values
    min: 2.0
    max: 8.0

  target_usage:
    distribution: uniform
    min: 0.015
    max: 0.04

  l1_coeff:
    distribution: log_uniform_values
    min: 0.000005  # 5e-6
    max: 0.0001    # 1e-4

  kl_warmup_steps:
    values: [500, 1000, 2000]

  expansion_factor:
    value: 10
